version: '3'
services:
  airflow-webserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dlt_pipeline:/opt/airflow/dlt_pipeline
      - ./dbt:/opt/airflow/dbt
  airflow-scheduler:
    build: .
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dlt_pipeline:/opt/airflow/dlt_pipeline
      - ./dbt:/opt/airflow/dbt
    command: ["airflow", "scheduler"]